phases:
  build:
    commands:
      - "echo Build started on `date`"
      - "echo Building the Docker image..."
      - "docker build -t artemis-web:$TAG ."
      - "docker tag artemis-web:$TAG 617072021155.dkr.ecr.us-east-1.amazonaws.com/artemis-web:$TAG"
  post_build:
    commands:
      - "echo Build completed on `date`"
      - "echo Pushing the Docker image..."
      - "docker push 617072021155.dkr.ecr.us-east-1.amazonaws.com/artemis-web:$TAG"
  pre_build:
    commands:
      - echo "Logging in to Amazon ECR..."
      - aws configure set aws_access_key_id $AWS_KEY
      - aws configure set aws_secret_access_key $AWS_SECRET
      - eval $(aws ecr get-login --no-include-email --region us-east-2 | sed 's;https://;;g')
version: 0.1