version: '3'
services:
  app:
    image: 617072021155.dkr.ecr.us-east-1.amazonaws.com/artemis-web:latest
    stdin_open: true
    ports:
      - "3000:3000"
    restart: always
    volumes:
      - .:/app